# Generated by Django 5.0.7 on 2025-02-02 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_user_username_update_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username_update_at",
            new_name="username_updated_at",
        ),
    ]
