# Generated by Django 5.0.7 on 2024-08-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comuse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
