# Generated by Django 5.0.7 on 2025-01-29 02:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comuse", "0004_piece_replyallowance_alter_piece_comment_reply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reply",
            new_name="Comment",
        ),
        migrations.RenameField(
            model_name="piece",
            old_name="comment",
            new_name="caption",
        ),
        migrations.RenameField(
            model_name="piece",
            old_name="replyAllowance",
            new_name="commentAllowance",
        ),
    ]
