# Generated by Django 5.0.7 on 2025-01-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comuse", "0005_rename_reply_comment_rename_comment_piece_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="comuse.piece",
            ),
        ),
    ]
